[package]
name = "ud-ast"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Abstract syntax tree for the .ud source language, with canonical pretty-printer."

[lints]
workspace = true

[dependencies]
ud-arch-x86 = { version = "0.1.5", path = "../ud-arch-x86" }
