[package]
name = "ud-arch-aarch64"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "AArch64 instruction decoder + minimal lifter for univdreams."

[lints]
workspace = true

[dependencies]
ud-core = { version = "0.3.0", path = "../ud-core" }
ud-ir = { version = "0.3.0", path = "../ud-ir" }
ud-arch-codec = { version = "0.3.0", path = "../ud-arch-codec" }
thiserror = "2"
